#!/bin/bash

#configuration of remote host to nagios server

#installing all the necessary packages
yum -y install httpd nrpe nagios-plugins-all wget

#adding check_mem plugin
cd /usr/lib64/nagios/plugins/
wget https://raw.githubusercontent.com/justintime/nagios-plugins/master/check_mem/check_mem.pl
mv check_mem.pl check_mem
chmod +x check_mem

#modify the nrpe file configuration to connect with the server
sed -i "s/allowed_hosts=127.0.0.1/allowed_hosts=127.0.0.1,10.128.0.0\/24/" /etc/nagios/nrpe.cfg
sed -i "s/dont_blame_nrpe=0/dont_blame_nrpe=1/" /etc/nagios/nrpe.cfg

#adjust nrpe command definitions
sed -i "215i command[check_disk]=\/usr\/lib64\/nagios\/plugins\/check_disk -w 20% -c 10% -p \/dev\/sda1" /etc/nagios/nrpe.cfg
sed -i "216i command[check_procs]=\/usr\/lib64\/nagios\/plugins\/check_procs -w 150 -c 200" /etc/nagios/nrpe.cfg
sed -i "217i command[check_mem]=/usr/lib64/nagios/plugins/check_mem  -f -w 10 -c 5" /etc/nagios/nrpe.cfg

#star and enable all the services
systemctl enable nrpe httpd
systemctl start nrpe httpd

