#!/bin/bash

#installing nagios packages
yum -y install nagios 

#turn off security enhace of linux
setenforce 0

#installing plugins and nagios client service
yum -y install nagios-plugins-all nrpe chech_nrpe wget

#enabling and stating services
systemctl enable nagios httpd nrpe
systemctl start nrpe
systemctl start nagios httpd

#create an admin user with password
htpasswd -ci /etc/nagios/passwd nagiosadmin <<< 123456

#modify the nrpe file configuration
sed -i "s/allowed_hosts=127.0.0.1/allowed_hosts=127.0.0.1,10.128.0.0\/24/" /etc/nagios/nrpe.cfg
sed -i "s/dont_blame_nrpe=0/dont_blame_nrpe=1/" /etc/nagios/nrpe.cfg 

#create a file configuration for the remote host
sh -c 'cat > /etc/nagios/conf.d/host1.cfg' << EF
#define host
define host {
        use             linux-server
        host_name       client-test
        alias           client-test
        address         10.128.0.3
        }

#DEFINING SERVICES

#PING service
define service{
        use                     generic-service
        host_name               client-test
        service_description     PING
        check_command           check_ping!100.0,20%!500.0,60%
        }

#HTTP services check
define service{
        use                     generic-service
        host_name               client-test
        service_description     HTTP
        check_command           check_http
        notifications_enabled   0
        }


#SSH service check
define service{
        use                     generic-service
        host_name               client-test
        service_description     SSH
        check_command           check_ssh
        notifications_enabled   0
        }

#Disk service check      
define service{
        use                     generic-service         
        host_name               client-test
        service_description     Root Partition
        check_command	        check_nrpe!check_disk!20%!10%!/
        }

#User service chech
define service{
        use                     generic-service      
        host_name               client-test
        service_description     Current Users
        check_command		check_nrpe!check_users!20!50
        }

#Proccess service check
define service{
        use                     generic-service        
        host_name               client-test
        service_description     Total Processes
        check_command	        check_nrpe!check_procs!250!400!RSZDT
        }

#Load Balance service check
define service{
        use                      generic-service        
        host_name                client-test
        service_description      Current Load
        check_command	         check_nrpe!check_load!5.0,4.0,3.0!10.0,6.0,4.0
        }
#Memory RAM service check
define service{
        use                      generic-service
        host_name                client-test
        service_description      Check RAM
        check_command            check_nrpe!check_mem
        }

EF

#add check_nrpe command definition
echo '# check_nrpe command definition
define command{
        command_name check_nrpe
        command_line $USER1$/check_nrpe -H $HOSTADDRESS$ -c $ARG1$
}
' >> /etc/nagios/objects/commands.cfg

echo '#Memory RAM service check
define service{
        use                      local-service
        host_name                localhost
        service_description      Check RAM
        check_command            check_nrpe!check_mem
        }
' >> /etc/nagios/object/localhost.cfg

#adjust built-in command definitions in nrpe.cfg
sed -i "215i command[check_disk]=\/usr\/lib64\/nagios\/plugins\/check_disk -w 20% -c 10% -p \/dev\/sda1" /etc/nagios/nrpe.cfg
sed -i "216i command[check_procs]=\/usr\/lib64\/nagios\/plugins\/check_procs -w 150 -c 200" /etc/nagios/nrpe.cfg
sed -i "217i command[check_mem]=/usr/lib64/nagios/plugins/check_mem  -f -w 20 -c 10" /etc/nagios/nrpe.cfg

#install check_mem
cd /usr/lib64/nagios/plugins/
wget https://raw.githubusercontent.com/justintime/nagios-plugins/master/check_mem/check_mem.pl
mv check_mem.pl check_mem
chmod +x check_mem

#restart all services
systemctl restart httpd nagios nrpe



