#!/bin/bash

#installing nagios packages
yum -y install nagios 

#turn off security enhace of linux
setenforce 0

#installing plugins and nagios client service
yum -y install nagios-plugins-all nrpe

#enabling and stating services
systemctl enable nagios httpd nrpe
systemctl start nrpe
systemctl start nagios httpd

#create an admin user with password
htpasswd -ci /etc/nagios/passwd nagiosadmin <<< 123456

#modify the nrpe file configuration
sed -i "s/allowed_hosts=127.0.0.1/allowed_hosts=127.0.0.1,10.128.0.0\/24/" /etc/nagios/nrpe.cfg
sed -i "s/dont_blame_nrpe=0/dont_blame_nrpe=1/" /etc/nagios/nrpe.cfg 

#create a file configuration for the remote host
sh -c 'cat > /etc/nagios/conf.d/host1.cfg' << EF
#define host
define host {
        use             linux-server
        host_name       client-test
        alias           client-test
        address         10.128.0.2
        }

#DEFINING SERVICES

#PING service
define service{
        use                     generic-service
        host_name               client-test
        service_description     PING
        check_command           check_ping!100.0,20%!500.0,60%
        }

#HTTP services check
define service{
        use                     generic-service
        host_name               client-test
        service_description     HTTP
        check_command           check_http
        notifications_enabled   0
        }

#SSH services check
define service{
        use                     generic-service
        host_name               client-test
        service_description     SSH
        check_command           check_ssh
        notifications_enabled   0
        }
EF

#restart all services
systemctl restart httpd nagios nrpe

